// ==================== IRONPRO FITNESS - CATÁLOGO ====================
// Productos importados del CSV con sus precios públicos.

import { Product } from './types';

export const ONDA_FITNESS_PRODUCTS: Product[] = [
  // ==================== PROTEINAS ====================
  {
    id: 'pro-best-whey-2lb',
    name: 'Best Whey - Proscience 2 lb',
    category: 'proteina',
    description: 'Proteína de alta calidad para construcción muscular.',
    price: 120000,
    originalPrice: 135000,
    image: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=500&q=80',
    stock: 50,
    rating: 4.8,
    reviews: 120,
    sku: 'BESTWHEY2',
    benefits: ['Absorción rápida', 'Construcción muscular', 'Excelente sabor'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'pro-best-vegan',
    name: 'Best Vegan - Proscience',
    category: 'proteina',
    description: 'Proteína 100% vegetal.',
    price: 120000,
    originalPrice: 130000,
    image: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=500&q=80',
    stock: 30,
    rating: 4.6,
    reviews: 85,
    sku: 'BESTVEG',
    benefits: ['Vegano', 'Fácil digestión', 'Aporte proteico completo'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'pro-mega-lite-1-2',
    name: 'Mega Lite - Nutrabier 1.2 lbs',
    category: 'proteina',
    description: 'Proteína ligera, ideal para definición.',
    price: 60000,
    originalPrice: 70000,
    image: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=500&q=80',
    stock: 45,
    rating: 4.5,
    reviews: 60,
    sku: 'MEGALITE12',
    benefits: ['Baja en calorías', 'Definición', 'Económica'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'pro-mega-gt-3-2',
    name: 'Mega G T - Nutrabier 3.2 lbs',
    category: 'proteina',
    description: 'Ganador de peso excelente para volumen.',
    price: 100000,
    originalPrice: 120000,
    image: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=500&q=80',
    stock: 25,
    rating: 4.7,
    reviews: 90,
    sku: 'MEGAGT32',
    benefits: ['Alto en calorías', 'Volumen extremo', 'Recuperación'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'pro-bipro-classic-2lb',
    name: 'Bi Pro Classic - Nutrabier 2 lb',
    category: 'proteina',
    description: 'Proteína aislada limpia para definición.',
    price: 100000,
    originalPrice: 115000,
    image: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=500&q=80',
    stock: 40,
    rating: 4.9,
    reviews: 210,
    sku: 'BIPRO2',
    benefits: ['Cero grasa', 'Cero azúcar', 'Aislada'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'pro-pancake-pro',
    name: 'Pancake Pro - Nutrabier',
    category: 'proteina',
    description: 'Mezcla para pancakes proteicos.',
    price: 35000,
    originalPrice: 40000,
    image: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=500&q=80',
    stock: 60,
    rating: 4.6,
    reviews: 150,
    sku: 'PANCAKEPRO',
    benefits: ['Desayuno fitness', 'Alto en proteína', 'Delicioso'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'pro-super-mega-2lb',
    name: 'Super Mega - Smart Muscle 2 lb',
    category: 'proteina',
    description: 'Proteína económica para ganancias musculares.',
    price: 55000,
    originalPrice: 65000,
    image: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=500&q=80',
    stock: 80,
    rating: 4.5,
    reviews: 320,
    sku: 'SUPERMEGA2',
    benefits: ['Mejor precio', 'Volumen', 'Efectiva'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'pro-titan-beef-2lb',
    name: 'Titan Beef - Smart Muscle 2 lb',
    category: 'proteina',
    description: 'Proteína de carne.',
    price: 55000,
    originalPrice: 65000,
    image: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=500&q=80',
    stock: 35,
    rating: 4.4,
    reviews: 80,
    sku: 'TITANBEEF2',
    benefits: ['Proteína de carne', 'Libre de lácteos', 'Fuerza'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  
  // ==================== CREATINAS ====================
  {
    id: 'crea-legend-pro',
    name: 'Legend Pro - Fitmafia',
    category: 'creatina',
    description: 'Creatina premium de alta asimilación.',
    price: 150000,
    originalPrice: 170000,
    image: 'https://images.unsplash.com/photo-1606403842097-8476fea00bed?w=500&q=80',
    stock: 25,
    rating: 4.9,
    reviews: 110,
    sku: 'LEGENDPRO',
    benefits: ['Fuerza extrema', 'Premium', 'Máxima absorción'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'crea-legend-fit',
    name: 'Legend Fit - Fitmafia',
    category: 'creatina',
    description: 'Creatina para resistencia y recuperación.',
    price: 120000,
    originalPrice: 135000,
    image: 'https://images.unsplash.com/photo-1606403842097-8476fea00bed?w=500&q=80',
    stock: 30,
    rating: 4.7,
    reviews: 95,
    sku: 'LEGENDFIT',
    benefits: ['Resistencia', 'Recuperación', 'Pura'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'crea-platinum-c',
    name: 'Platinum C - Muscletech',
    category: 'creatina',
    description: 'Creatina micronizada Muscletech.',
    price: 150000,
    originalPrice: 165000,
    image: 'https://images.unsplash.com/photo-1606403842097-8476fea00bed?w=500&q=80',
    stock: 40,
    rating: 4.9,
    reviews: 450,
    sku: 'PLATINUMC',
    benefits: ['Micronizada', 'Calidad garantizada', 'Fuerza'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'crea-creatina-3',
    name: 'Creatina 3 - Nutrabier',
    category: 'creatina',
    description: 'Opción más económica de creatina.',
    price: 20000,
    originalPrice: 25000,
    image: 'https://images.unsplash.com/photo-1606403842097-8476fea00bed?w=500&q=80',
    stock: 100,
    rating: 4.5,
    reviews: 350,
    sku: 'CREA3',
    benefits: ['Super económica', 'Efectiva', 'Ideal para empezar'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'crea-creatina-c',
    name: 'Creatina C - Nutrabier',
    category: 'creatina',
    description: 'Creatina C.',
    price: 45000,
    originalPrice: 55000,
    image: 'https://images.unsplash.com/photo-1606403842097-8476fea00bed?w=500&q=80',
    stock: 60,
    rating: 4.6,
    reviews: 120,
    sku: 'CREAC',
    benefits: ['Buen valor', 'Fuerza', 'Pura'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'crea-mic-300',
    name: 'Creatine Mic 300 - Smart Muscle',
    category: 'creatina',
    description: 'Creatina micronizada 300g.',
    price: 60000,
    originalPrice: 70000,
    image: 'https://images.unsplash.com/photo-1606403842097-8476fea00bed?w=500&q=80',
    stock: 45,
    rating: 4.7,
    reviews: 180,
    sku: 'CREAMIC300',
    benefits: ['Micronizada', 'Excelente precio', 'Rendimiento'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'crea-emi',
    name: 'Emi Creatin - Otros',
    category: 'creatina',
    description: 'Creatina básica.',
    price: 25000,
    originalPrice: 30000,
    image: 'https://images.unsplash.com/photo-1606403842097-8476fea00bed?w=500&q=80',
    stock: 75,
    rating: 4.3,
    reviews: 90,
    sku: 'EMICREA',
    benefits: ['Económica', 'Fuerza', 'Básica'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'crea-100',
    name: 'Creatina 100 - Healthy',
    category: 'creatina',
    description: 'Creatina 100 servings.',
    price: 70000,
    originalPrice: 85000,
    image: 'https://images.unsplash.com/photo-1606403842097-8476fea00bed?w=500&q=80',
    stock: 40,
    rating: 4.8,
    reviews: 210,
    sku: 'CREA100H',
    benefits: ['Larga duración', '100 servicios', 'Pura'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  
  // ==================== PRE-ENTRENOS ====================
  {
    id: 'pre-fase-20',
    name: 'Fase 20 M P - Fitmafia',
    category: 'pre-entreno',
    description: 'Pre-entreno potente para rutinas intensas.',
    price: 105000,
    originalPrice: 120000,
    image: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=500&q=80',
    stock: 35,
    rating: 4.7,
    reviews: 140,
    sku: 'FASE20',
    benefits: ['Energía extrema', 'Enfoque', 'Bombeo'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'pre-intenze',
    name: 'Intenze PR - Nutrabier',
    category: 'pre-entreno',
    description: 'Energía sostenida.',
    price: 50000,
    originalPrice: 60000,
    image: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=500&q=80',
    stock: 55,
    rating: 4.5,
    reviews: 90,
    sku: 'INTENZEPR',
    benefits: ['Buen precio', 'Energía limpia', 'Resistencia'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'pre-venom',
    name: 'Venom Pre - Dragon Pharma',
    category: 'pre-entreno',
    description: 'Pre-entreno de élite mundial.',
    price: 150000,
    originalPrice: 170000,
    image: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=500&q=80',
    stock: 20,
    rating: 4.9,
    reviews: 310,
    sku: 'VENOMPRE',
    benefits: ['Extremo', 'Calidad premium', 'Fuerza'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'pre-psychotic',
    name: 'Psychotic T - Insane Lab',
    category: 'pre-entreno',
    description: 'Energía insana para los más exigentes.',
    price: 120000,
    originalPrice: 140000,
    image: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=500&q=80',
    stock: 28,
    rating: 4.8,
    reviews: 420,
    sku: 'PSYCHOTIC',
    benefits: ['Estimulante fuerte', 'Enfoque láser', 'Larga duración'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ==================== AMINOÁCIDOS ====================
  {
    id: 'ami-army-bcaa',
    name: 'Army BCAA - Proscience',
    category: 'aminoacidos',
    description: 'BCAAs para recuperación muscular.',
    price: 115000,
    originalPrice: 130000,
    image: 'https://images.unsplash.com/photo-1579722820308-d74e571900a9?w=500&q=80',
    stock: 40,
    rating: 4.8,
    reviews: 215,
    sku: 'ARMYBCAA',
    benefits: ['Recuperación', 'Anticatabólico', 'Hidratación'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ami-alpha-bcaa',
    name: 'Alpha BCAA - Smart Muscle',
    category: 'aminoacidos',
    description: 'Aminos esenciales.',
    price: 70000,
    originalPrice: 85000,
    image: 'https://images.unsplash.com/photo-1579722820308-d74e571900a9?w=500&q=80',
    stock: 50,
    rating: 4.6,
    reviews: 130,
    sku: 'ALPHABCAA',
    benefits: ['Buen valor', 'Recuperación', 'Resistencia'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ==================== QUEMADORES ====================
  {
    id: 'que-hydroxycut',
    name: 'Hydroxycut - Muscletech',
    category: 'quemador',
    description: 'Quemador de grasa top ventas mundial.',
    price: 120000,
    originalPrice: 140000,
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500&q=80',
    stock: 35,
    rating: 4.7,
    reviews: 310,
    sku: 'HYDROXYCUT',
    benefits: ['Termogénico', 'Pérdida de peso', 'Energía'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'que-burner-sta',
    name: 'Burner Sta - Nutrabier',
    category: 'quemador',
    description: 'Potente fórmula quemagrasa.',
    price: 140000,
    originalPrice: 160000,
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500&q=80',
    stock: 25,
    rating: 4.8,
    reviews: 180,
    sku: 'BURNERSTA',
    benefits: ['Quema grasa', 'Control apetito', 'Definición'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'que-black-viper',
    name: 'Black Viper - Dragon Pharma',
    category: 'quemador',
    description: 'Quemador extremo para competidores.',
    price: 110000,
    originalPrice: 130000,
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500&q=80',
    stock: 20,
    rating: 4.9,
    reviews: 240,
    sku: 'BLACKVIPER',
    benefits: ['Extremo', 'Energía', 'Definición rápida'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ==================== VITAMINAS / NUTRICIÓN ====================
  {
    id: 'vit-omega3',
    name: 'Omega 3 P - Proscience',
    category: 'vitaminas',
    description: 'Ácidos grasos esenciales.',
    price: 27000,
    originalPrice: 35000,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&q=80',
    stock: 80,
    rating: 4.9,
    reviews: 410,
    sku: 'OMEGA3P',
    benefits: ['Salud cardiovascular', 'Articulaciones', 'Económico'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'vit-multivitam',
    name: 'Multivitam - Muscletech',
    category: 'vitaminas',
    description: 'Multivitamínico completo.',
    price: 50000,
    originalPrice: 65000,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&q=80',
    stock: 50,
    rating: 4.8,
    reviews: 290,
    sku: 'MULTIVITAM',
    benefits: ['Completo', 'Inmunidad', 'Recuperación'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
